language: android

jdk:
- oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - extra-google-m2repository
    - build-tools-27.0.3
    - android-27

env:
    global:
    - TERM=dumb

script: ./gradlew check

after_success:
    - ./gradlew jacocoTestReport
    - ./gradlew coveralls
